MongoDB migraties uitvoeren tijdens helm upgrade
kadaster-labs/sensrnet-helm-charts pull request #43
Opened 2022-01-18 16:55 UTC by kad-floriw

Toevoegen van een job, die de nog-niet uitgevoerde mongoDB migraties uitvoert. Deze wordt uitgevoerd na een helm install / upgrade van de backend, door middel van een helm hook.

2022-01-19 14:49 UTC, marcvanandel commented
Fancy! Dit ziet er wel goed uit ... maar hoe test ik dit? Kan ik gewoon een install doen in mijn lokale cluster?

2022-01-19 17:45 UTC, kad-floriw commented
> Afhankelijk van je client ... maar ik krijg deze melding:
> 
> ```shell
> batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
> ```

Dit heeft te maken met de CronJob die gebruikt wordt om de eventstore op te ruimen, dat is niet gerelateerd. Maar kan op zich wel meegenomen worden in dit PR!

2022-01-20 08:52 UTC, kad-busses commented
Gaaf! 😎 Zal er naar kijken en testen. Schieten me alvast een paar vragen te binnen:

1. Kunnen we een rollback kunnen doen in dit scenario? Ben hier zelf over na aan het denken, maar had je daar zelf ook aan gedacht? Het mooie van K8s is natuurlijk dat we eenvoudig tussen versies kunnen switchen en eenvoudig kunnen terugrollen, mocht er een fout in een nieuwe versie zitten
2. En nog een stapje terug: Had je ook gekeken naar de optie om de view opnieuw op te bouwen? Blijft een beetje vreemd voelen om de projectie te bewerken, doen we dan eigenlijk niet dubbel werk?
3. Denk niet dat de `migrate: true` hoeven toe te voegen, daarmee kunnen we/partijen immers ook de migrate onterecht skippen 😉

Kubernetes v1.25 is nu nog niet uit, verwachting is later dit jaar. De ES cronjob hoeft die niet direct, maar mag in een andere PR 😄

2022-01-20 09:27 UTC, kad-floriw commented
> Gaaf! 😎 Zal er naar kijken en testen. Schieten me alvast een paar vragen te binnen:
> 
> 1. Kunnen we een rollback kunnen doen in dit scenario? Ben hier zelf over na aan het denken, maar had je daar zelf ook aan gedacht? Het mooie van K8s is natuurlijk dat we eenvoudig tussen versies kunnen switchen en eenvoudig kunnen terugrollen, mocht er een fout in een nieuwe versie zitten
> 2. En nog een stapje terug: Had je ook gekeken naar de optie om de view opnieuw op te bouwen? Blijft een beetje vreemd voelen om de projectie te bewerken, doen we dan eigenlijk niet dubbel werk?
> 3. Denk niet dat de `migrate: true` hoeven toe te voegen, daarmee kunnen we/partijen immers ook de migrate onterecht skippen 😉
> 
> Kubernetes v1.25 is nu nog niet uit, verwachting is later dit jaar. De ES cronjob hoeft die niet direct, maar mag in een andere PR 😄

1) Dat zit er nog niet in, het lijkt mij vrij ingewikkeld om dat te implementeren, en bij andere projecten hebben we het ook niet. Misschien een ticket op de backlog van maken?
2) Dat zou in principe ook kunnen, maar dan moet eerst de database geleegd worden waarna alle events opnieuw uitgevoerd worden. Ik vind dat zelf een ietwat omslachtige methode, maar ik weet niet of het binnen event-sourcing gebruikelijker is, misschien weet jij dit @marcvanandel?
3) Prima idee, ik zal dat implementeren en testen.

2022-01-20 11:30 UTC, kad-floriw commented
Ik testte nog met een oude versie van het deploy_local_images.sh script. Met de nieuwe versie waarin de backend in 1 stap gedeployed wordt is het eenvoudiger, ik heb de hook aangepast naar post-install, post-upgrade, en de migrate optie verwijderd!

2022-01-20 18:07 UTC, kad-busses requested changes
Gaaf, heel nice. De Helm Chart Hook is hier een perfecte aanpak voor! 👌 Heb alleen een paar kleine opmerkingen toegevoegd.

Nog voortbordurend op eerdere discussie (hoeft verder niet meer opgepakt te worden in deze PR):
1. Waar ik naar op zoek was, was `migrate-mongo down` 😁. Gelukkig is `migrate-mongo` gewoon beschikbaar in de `registry-backend` container zie ik. Als iemand echt tegen problemen aanloopt, kunnen ze via de backend ssh'en en de projectie ongedaan maken. Ga er vanuit dat het niet nodig is, maar dan is er wel een strategie mocht het zover komen
2. Als de projectie-database alleen projecties opslaat, is een handige strategie om een nieuwe database op te starten, die de projectie opnieuw op te laten bouwen, en wanneer die beschikbaar is de oude database af te breken. Gezien wij de user management ook in dezelfde db doen, is dat geen goede optie. 
In het huidige scenario moeten we alleen heel zeker zijn dat de migratie correct is, anders kunnen we problemen krijgen met het updaten van de projectie bij nieuwe events. Dit kun je daardoor ook zien als een omslachtige methode, gezien de juiste informatie al in de events zelf staat 😉

2022-01-20 22:50 UTC, kad-floriw commented
Dat maakt het nog iets netter inderdaad.

2022-01-21 09:30 UTC, merged